version: '3.8'

services:
  backend:
    build: ./backend
    container_name: etegami_backend
    restart: always
    env_file: ./.env         # ← lê tudo do .env da raiz
    ports:
      - "3000:3000"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
      - ./passwords.txt:/app/passwords.txt

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}   # ← passa pro Dockerfile em build time
    container_name: etegami_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
